# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/dlfs',
                'doc_host': 'https://Fflath.github.io',
                'git_url': 'https://github.com/Fflath/dlfs',
                'lib_path': 'dlfs'},
  'syms': {'dlfs.core': {'dlfs.core.foo': ('core.html#foo', 'dlfs/core.py')}}}