# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/dlfs',
                'doc_host': 'https://Fflath.github.io',
                'git_url': 'https://github.com/Fflath/dlfs',
                'lib_path': 'dlfs'},
  'syms': { 'dlfs.Dataset': { 'dlfs.Dataset.Dataset': ('data.html#dataset', 'dlfs/Dataset.py'),
                              'dlfs.Dataset.Dataset.__getitem__': ('data.html#dataset.__getitem__', 'dlfs/Dataset.py'),
                              'dlfs.Dataset.Dataset.__init__': ('data.html#dataset.__init__', 'dlfs/Dataset.py'),
                              'dlfs.Dataset.Dataset.__len__': ('data.html#dataset.__len__', 'dlfs/Dataset.py'),
                              'dlfs.Dataset.get_dataset': ('data.html#get_dataset', 'dlfs/Dataset.py')},
            'dlfs.core': {'dlfs.core.foo': ('core.html#foo', 'dlfs/core.py')},
            'dlfs.training': { 'dlfs.training.Dataset': ('data.html#dataset', 'dlfs/training.py'),
                               'dlfs.training.Dataset.__getitem__': ('data.html#dataset.__getitem__', 'dlfs/training.py'),
                               'dlfs.training.Dataset.__init__': ('data.html#dataset.__init__', 'dlfs/training.py'),
                               'dlfs.training.Dataset.__len__': ('data.html#dataset.__len__', 'dlfs/training.py'),
                               'dlfs.training.get_dataset': ('data.html#get_dataset', 'dlfs/training.py')}}}