# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_Trainer.ipynb.

# %% auto 0
__all__ = ['Optimizer']

# %% ../nbs/02_Trainer.ipynb 2
from . import *

# %% ../nbs/02_Trainer.ipynb 3
from torch import tensor,nn,no_grad
import torch
import torch.nn.functional as F
import fastcore.all as fc


# %% ../nbs/02_Trainer.ipynb 5
class Optimizer():
    def __init__(self, params, lr=0.5): self.params,self.lr=list(params),lr

    def step(self):
        with no_grad():
            for p in self.params: p -= p.grad * self.lr

    def zero_grad(self):
        for p in self.params: p.grad.data.zero_()
